[services.rpi]
type     = "sftp"
host     = "rpi.local"
user     = "nurlan"
port     = 22
key_file = "~/.ssh/id_ed25519"

[services.mac]
type     = "sftp"
host     = "macbook.local"
user     = "nurlan"
port     = 22
key_file = "~/.ssh/id_ed25519"

[services.work]
type     = "sftp"
host     = "nurlans-mac-mini.local"
user     = "nurlan"
port     = 22
key_file = "~/.ssh/id_ed25519"
